<a href="https://colab.research.google.com/github/Karlajack/pydata_analysis/blob/main/Numpy_Exercise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.Import the numpy package under the name np

In [3]:
import numpy as np

2.Print the numpy version and the configuration

In [ ]:
np.__version__

'1.25.2'

Create a null vector of size 10

In [ ]:
array=np.zeros(10,dtype=int)
array


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

**How to find the memory size of any array**

In [ ]:
array.nbytes



80

 How to get the documentation of the numpy add function from the command line

In [ ]:
(np.info(np. add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

Create a null vector of size 10 but the fifth value which is 1

In [ ]:
array[5]=1
print(array)

[0 0 0 0 0 1 0 0 0 0]


Create a vector with values ranging from 10 to 49

In [ ]:
v = np.arange(10, 50)
v

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

Reverse a vector (first element becomes last)

In [ ]:
v=v[::-1]
v

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

 Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
m = np.arange(0, 9).reshape(3, 3)
print(m)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


Find indices of non-zero elements from [1,2,0,0,4,0]

In [ ]:
y=np.array([1,2,0,0,4,0])
zero_ele =np.where(y==0)
print(zero_ele)

(array([2, 3, 5]),)


Create a 3x3 identity matrix

In [ ]:
w=np.identity(3)
w

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Create a 3x3x3 array with random values

In [ ]:
z = np.random.random((3, 3, 3))
z

array([[[0.5335466 , 0.14010826, 0.11923755],
        [0.74684065, 0.53168463, 0.54448506],
        [0.00893915, 0.95862027, 0.39972576]],

       [[0.52452459, 0.47293956, 0.63302628],
        [0.90677683, 0.13385221, 0.58929395],
        [0.32145554, 0.08905595, 0.810854  ]],

       [[0.67901774, 0.22384969, 0.22059219],
        [0.07062621, 0.94177583, 0.03614413],
        [0.72777567, 0.54780172, 0.48324413]]])

Create a 10x10 array with random values and find the minimum and maximum values

In [ ]:
t = np.random.random((10, 10))
t



array([[0.02052155, 0.57789612, 0.56663975, 0.31127845, 0.24263276,
        0.30157711, 0.11305205, 0.00686927, 0.36685554, 0.61571316],
       [0.13530709, 0.96438783, 0.32258605, 0.31692836, 0.17364009,
        0.51885233, 0.54787207, 0.38059313, 0.92996457, 0.62502107],
       [0.50485513, 0.07459415, 0.59571678, 0.26873848, 0.53556046,
        0.15261405, 0.07323367, 0.91028619, 0.71950745, 0.80923162],
       [0.57731785, 0.1771812 , 0.63422914, 0.14652785, 0.99380958,
        0.63555366, 0.73264218, 0.73545067, 0.81485627, 0.69352672],
       [0.77591706, 0.5044719 , 0.27518457, 0.63947659, 0.14261937,
        0.12584614, 0.8851797 , 0.78956974, 0.85673258, 0.39036401],
       [0.52638225, 0.77489668, 0.51386329, 0.44749133, 0.39081395,
        0.05772803, 0.55100236, 0.26732483, 0.83065436, 0.96509013],
       [0.46142926, 0.99075683, 0.9682679 , 0.44366486, 0.41395783,
        0.87185152, 0.48697623, 0.34099277, 0.59382865, 0.73905018],
       [0.7649893 , 0.5219902 , 0.9730271

In [ ]:
min=np.min(t)
min


0.006869266539336505

In [ ]:
max=np.max(t)
max

0.9938095812408713

 Create a random vector of size 30 and find the mean value

In [5]:
d=np.random.random(30)
d

array([0.98153735, 0.96407549, 0.05754321, 0.61429215, 0.7940727 ,
       0.81009696, 0.15141909, 0.09618948, 0.51738633, 0.08619627,
       0.98240868, 0.69782342, 0.89308676, 0.57824606, 0.46116415,
       0.54398021, 0.35397583, 0.47611398, 0.81996555, 0.84800315,
       0.55244727, 0.98166475, 0.29933743, 0.02080265, 0.83922864,
       0.08272156, 0.88795672, 0.19179194, 0.09917537, 0.49438161])

Create a random vector of size 30 and find the mean value

In [6]:
mean=np.mean(d)
print (mean)

0.539236158462856


Create a 2d array with 1 on the border and 0 inside

In [22]:
p= np.ones((6, 6))
print(p)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [23]:
p[1:-1,1:-1] = 0
print(p)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]
