<a href="https://colab.research.google.com/github/Karlajack/pydata_analysis/blob/main/Numpy_Exercise_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

31. How to ignore all numpy warnings (not recommended)?

In [8]:
defaults = np.seterr(all="ignore")
Z = np.ones(1)/0

32. Is the following expressions true?

In [9]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

33. How to get the dates of yesterday, today and tomorrow?

In [13]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

print(yesterday)
print(today)
print(tomorrow)

2024-03-27
2024-03-28
2024-03-29


34. How to get all the dates corresponding to the month of July 2016?

In [14]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


35. How to compute ((A+B)*(-A/2)) in place (without copy)?

In [15]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

36. Extract the integer part of a random array of positive numbers using 4 different methods

In [16]:
Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[0. 2. 1. 1. 4. 9. 5. 0. 4. 0.]
[0. 2. 1. 1. 4. 9. 5. 0. 4. 0.]
[0. 2. 1. 1. 4. 9. 5. 0. 4. 0.]
[0 2 1 1 4 9 5 0 4 0]
[0. 2. 1. 1. 4. 9. 5. 0. 4. 0.]


37. Create a 5x5 matrix with row values ranging from 0 to 4

In [17]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


38. Consider a generator function that generates 10 integers and use it to build an array

In [18]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


39. Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [19]:
Z = np.linspace(0,1,12,endpoint=True)[1:-1]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


40. Create a random vector of size 10 and sort it

In [20]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.14568431 0.27838569 0.39858312 0.39933123 0.42441815 0.512077
 0.8195467  0.83721315 0.8743853  0.9726845 ]


41. How to sum a small array faster than np.sum?

In [21]:
Z = np.arange(10)
np.add.reduce(Z)

45

Consider two random array A anb B, check if they are equal

In [27]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


43. Make an array immutable (read-only)

In [29]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

In [30]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[1.04936466 0.85305389 0.28664311 0.7215984  0.85657946 0.54465742
 0.70921279 0.5992028  0.3305838  0.85723838]
[0.76873623 1.5034632  1.54486206 0.23089884 0.31642882 0.76422937
 0.98174256 1.46392682 1.33482662 0.76332425]


45. Create random vector of size 10 and replace the maximum value by 0

In [31]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.06559523 0.75237111 0.48564697 0.78441364 0.80173635 0.78177658
 0.04364876 0.         0.55261729 0.95080037]
